name: ci

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Build
      run: |
        source $CONDA/bin/activate
        poetry install
    - name: pytest
      run: |
        source $CONDA/bin/activate
        poetry run pytest 
    - name: black
      run: |
        source $CONDA/bin/activate
        poetry run black --check src tests
    - name: mypy
      run: |
        source $CONDA/bin/activate
        poetry run mypy src tests
    - name: flake8
      run: |
        source $CONDA/bin/activate
        poetry run flake8 src tests
